name: build and publish snapshot
on:
  push:
    branches:
      - main
    paths:
      - '**.kt'
      - '**.kts'
      - '.github/workflows/publish-snapshot.yml'
      - '!tests/**'
      - '!examples/**'

  # 手动触发工作流
  workflow_dispatch:
env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: zulu
  GRADLE_VERSION: 9.0.0
  IS_CI: true
  IS_SNAPSHOT: true
  SIGNING_KEY_ID: ${{ secrets.GPG_KEY_ID }}
  GPG_KEY_CONTENTS: ${{ secrets.GPG_PRI_KEY }}
  SIGNING_PASSWORD: ${{ secrets.GPG_PASSWORD }}
  MAVEN_CENTRAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
  MAVEN_CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
  GRADLE_OPTS: "-Dfile.encoding=UTF-8"

jobs:
  test:
    name: Build test
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
      - run: gradle assemble build test allTests -s

  publish:
    name: Publish Snapshot
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Publish snapshot to Maven Central
        run: gradle publishToMavenCentral -s --warning-mode all -x test --build-cache --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_org.gradle.jvmargs: "-XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8"
          ORG_GRADLE_PROJECT_org.gradle.daemon: "false"
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ env.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ env.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ env.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ env.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ env.GPG_KEY_CONTENTS }}
